# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YandexMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YandexMap
pod 'YandexMapsMobile', '4.2.2-full'
end
